FROM ubuntu:18.04
MAINTAINER Davide

RUN apt-get update
RUN apt-get install -y build-essential gdb lcov git vim wget htop unzip cmake
RUN apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev libglfw3-dev

