cc_library(
    name = 'core',
    hdrs = glob(['core/*.h']),
    strip_include_prefix = '.',
    linkstatic = True,
    visibility = ["//visibility:public"],
)
cc_library(
    name = 'math',
    hdrs = glob(['math/*.h']),
    strip_include_prefix = '.',
    linkstatic = True,
    visibility = ["//visibility:public"],
)
